name: "Prod"
on:
  release:
    types: [created]

  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/timebot

jobs:
  build:
    name: Tag image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${{ steps.tag.outputs.tag }} --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_NAME:${{ steps.tag.outputs.tag }}
    outputs:
      docker_tag: ${{ steps.tag.outputs.tag }}
  plan:
    name: "Terraform Prod plan"
    runs-on: ubuntu-latest
    environment:
      name: "prod-plan"
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.11/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt
      - name: Plan Timebot prod deployment
        working-directory: infra/terragrunt/prod/timebot/
        run: |
          terragrunt plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
          TF_VAR_acr_subscription_id: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
          TF_VAR_timebot_image: "${{ env.IMAGE_NAME }}:${{ needs.build.outputs.docker_tag }}"
          TF_VAR_app_token: ${{ secrets.PROD_PLAN_APP_TOKEN }}
          TF_VAR_bot_user_token: ${{ secrets.PROD_PLAN_BOT_TOKEN }}
          TF_VAR_harvest_token: ${{ secrets.PROD_HARVEST_TOKEN }}
          TF_VAR_harvest_id: ${{ secrets.PROD_HARVEST_ID }}
          TF_VAR_harvest_url: "https://api.harvestapp.com/v2/"
  apply:
    name: "Terraform Prod Apply"
    runs-on: ubuntu-latest
    environment:
      name: "prod"
    needs: [build, plan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.11/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt
      - name: Deploy Timebot to Prod
        working-directory: infra/terragrunt/prod/timebot/
        run: |
          terragrunt apply --terragrunt-non-interactive -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
          TF_VAR_acr_subscription_id: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
          TF_VAR_timebot_image: "${{ env.IMAGE_NAME }}:${{ needs.build.outputs.docker_tag }}"
          TF_VAR_app_token: ${{ secrets.PROD_APP_TOKEN }}
          TF_VAR_bot_user_token: ${{ secrets.PROD_BOT_TOKEN }}
          TF_VAR_harvest_token: ${{ secrets.PROD_HARVEST_TOKEN }}
          TF_VAR_harvest_id: ${{ secrets.PROD_HARVEST_ID }}
          TF_VAR_harvest_url: "https://api.harvestapp.com/v2/"