name: "Destroy-NP"
on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/timebot

jobs:
  plan:
    name: "Terraform Plan - Destroy"
    runs-on: ubuntu-latest
    environment:
      name: "nonprod"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.12/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt
      - name: Unlock Timebot
        working-directory: infra/terragrunt/nonprod/timebot/
        run: |
          terragrunt force-unlock -force 7ee8ff6e-63b0-0e3c-1f48-4fe90c7ab8de
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_NONPROD_SUBSCRIPTION_ID }}
          TF_VAR_acr_subscription_id: ${{ secrets.AZURE_NONPROD_SUBSCRIPTION_ID }}
          TF_VAR_timebot_image: "${{ env.IMAGE_NAME }}:${{ needs.build.outputs.docker_tag }}"
          TF_VAR_app_token: ${{ secrets.NONPROD_APP_TOKEN }}
          TF_VAR_bot_user_token: ${{ secrets.NONPROD_BOT_TOKEN }}
          TF_VAR_harvest_token: ${{ secrets.NONPROD_HARVEST_TOKEN }}
          TF_VAR_harvest_id: ${{ secrets.NONPROD_HARVEST_ID }}
          TF_VAR_harvest_url: "https://api.harvestapp.com/v2/"
      - name: Plan Timebot Destroy
        working-directory: infra/terragrunt/nonprod/timebot/
        run: |
          terragrunt plan -destroy
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_NONPROD_SUBSCRIPTION_ID }}
          TF_VAR_acr_subscription_id: ${{ secrets.AZURE_NONPROD_SUBSCRIPTION_ID }}
          TF_VAR_timebot_image: "${{ env.IMAGE_NAME }}:${{ needs.build.outputs.docker_tag }}"
          TF_VAR_app_token: ${{ secrets.NONPROD_APP_TOKEN }}
          TF_VAR_bot_user_token: ${{ secrets.NONPROD_BOT_TOKEN }}
          TF_VAR_harvest_token: ${{ secrets.NONPROD_HARVEST_TOKEN }}
          TF_VAR_harvest_id: ${{ secrets.NONPROD_HARVEST_ID }}
          TF_VAR_harvest_url: "https://api.harvestapp.com/v2/"
  apply:
    name: "Terraform Apply - Destroy"
    runs-on: ubuntu-latest
    environment:
      name: "nonprod"
    needs: [plan]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.12/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt
      - name: Destroy Timebot to Nonprod
        working-directory: infra/terragrunt/nonprod/timebot/
        run: |
          terragrunt destroy --terragrunt-non-interactive -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: "1b4a4fed-fed8-4823-a8a0-3d5cea83d122"
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_NONPROD_SUBSCRIPTION_ID }}
          TF_VAR_acr_subscription_id: ${{ secrets.AZURE_NONPROD_SUBSCRIPTION_ID }}
          TF_VAR_timebot_image: "${{ env.IMAGE_NAME }}:${{ needs.build.outputs.docker_tag }}"
          TF_VAR_app_token: ${{ secrets.NONPROD_APP_TOKEN }}
          TF_VAR_bot_user_token: ${{ secrets.NONPROD_BOT_TOKEN }}
          TF_VAR_harvest_token: ${{ secrets.NONPROD_HARVEST_TOKEN }}
          TF_VAR_harvest_id: ${{ secrets.NONPROD_HARVEST_ID }}
          TF_VAR_harvest_url: "https://api.harvestapp.com/v2/"
